markdown: rdiscount
highlighter: pygments

relative_permalinks: false

minItemsToShowToc: 2

# Needed only when generate Apple Help
showToggleButton: false
prefixDir: ../../common/

exclude: ['mas', '*.sh', 'params.json']